[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 50
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = true
ignored_error_codes = [6546, 1878, 2394]

[profile.default.fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"

# See more config options https://book.getfoundry.sh/reference/config/overview