[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000
auto_detect_solc = true
auto_detect_remappings = true

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"

localhost = "http://127.0.0.1:8545"

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"

# See more config options https://book.getfoundry.sh/reference/config/overview